//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:/Repo/Mods/Stationeers/Entropy/Assets/Scripts/MIPSParser/MIPS.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MIPSParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
public interface IMIPSListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] MIPSParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] MIPSParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] MIPSParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] MIPSParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] MIPSParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] MIPSParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefine([NotNull] MIPSParser.DefineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefine([NotNull] MIPSParser.DefineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlias([NotNull] MIPSParser.AliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlias([NotNull] MIPSParser.AliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] MIPSParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] MIPSParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.define_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefine_target([NotNull] MIPSParser.Define_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.define_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefine_target([NotNull] MIPSParser.Define_targetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.alias_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlias_target([NotNull] MIPSParser.Alias_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.alias_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlias_target([NotNull] MIPSParser.Alias_targetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] MIPSParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] MIPSParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] MIPSParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] MIPSParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperand([NotNull] MIPSParser.OperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperand([NotNull] MIPSParser.OperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] MIPSParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] MIPSParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegister([NotNull] MIPSParser.RegisterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegister([NotNull] MIPSParser.RegisterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.device"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDevice([NotNull] MIPSParser.DeviceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.device"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDevice([NotNull] MIPSParser.DeviceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.hash"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHash([NotNull] MIPSParser.HashContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.hash"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHash([NotNull] MIPSParser.HashContext context);
}
