using System;
using System.IO;
using System.Linq;
using System.Reflection;

if (args.Length < 3)
{
	Console.Error.WriteLine("Usage: AttrDump <assemblyPath> <referencedAssemblies> <outFile>");
	return 2;
}

var assemblyPath = Path.GetFullPath(args[0]);
var referencedAssemblies = Path.GetFullPath(args[1]);
var outputPath = Path.GetFullPath(args[2]);

var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
// Include runtime assemblies + target assembly directory so resolver can find referenced types if needed.
var paths = Directory.EnumerateFiles(runtimeDir, "*.dll")
	.Concat(referencedAssemblies.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries))
	.Append(assemblyPath)
	.Distinct(StringComparer.OrdinalIgnoreCase)
	.ToArray();
var resolver = new PathAssemblyResolver(paths);
using var loadContext = new MetadataLoadContext(resolver);

var asm = loadContext.LoadFromAssemblyPath(assemblyPath);
var id = asm.GetName().Name;
var customAttributes = CustomAttributeData.GetCustomAttributes(asm);
var title = customAttributes.FirstOrDefault(x => x.AttributeType.Name == nameof(AssemblyTitleAttribute))?
	.ConstructorArguments[0].Value?.ToString() ?? id;
var description = customAttributes.FirstOrDefault(x => x.AttributeType.Name == nameof(AssemblyDescriptionAttribute))?
	.ConstructorArguments[0].Value?.ToString() ?? "";
var version = customAttributes.FirstOrDefault(x => x.AttributeType.Name == nameof(AssemblyInformationalVersionAttribute))?.ConstructorArguments[0].Value?.ToString()
	?? customAttributes.FirstOrDefault(x => x.AttributeType.Name == nameof(AssemblyVersionAttribute))?.ConstructorArguments[0].Value?.ToString() ?? "1.0";
var author = customAttributes.FirstOrDefault(x => x.AttributeType.Name == nameof(AssemblyCompanyAttribute))?.ConstructorArguments[0].Value?.ToString() ?? "";
var inGameDescription = customAttributes.FirstOrDefault(x => x.AttributeType.Name == nameof(AssemblyMetadataAttribute)
	&& x.ConstructorArguments[0].Value?.ToString() == "InGameDescription")?.ConstructorArguments[1].Value?.ToString() ?? "";
var workshopHandle = customAttributes.FirstOrDefault(x => x.AttributeType.Name == nameof(AssemblyMetadataAttribute)
	&& x.ConstructorArguments[0].Value?.ToString() == "WorkshopHandle")?.ConstructorArguments[1].Value?.ToString();
var changelog = customAttributes.FirstOrDefault(x => x.AttributeType.Name == nameof(AssemblyMetadataAttribute)
	&& x.ConstructorArguments[0].Value?.ToString() == "ChangeLog")?.ConstructorArguments[1].Value?.ToString();
var tags = customAttributes.Where(x => x.AttributeType.Name == nameof(AssemblyMetadataAttribute)
	&& x.ConstructorArguments[0].Value?.ToString() == "Tag").Select(x => x.ConstructorArguments[1].Value?.ToString()).ToArray();
var dependencies = customAttributes.Where(x => x.AttributeType.Name == nameof(AssemblyMetadataAttribute)
	&& x.ConstructorArguments[0].Value?.ToString() == "DependsOn").Select(x => x.ConstructorArguments[1].Value?.ToString());
var orderBefore = customAttributes.Where(x => x.AttributeType.Name == nameof(AssemblyMetadataAttribute)
	&& x.ConstructorArguments[0].Value?.ToString() == "OrderBefore").Select(x => x.ConstructorArguments[1].Value?.ToString()).ToArray();
var orderAfter = customAttributes.Where(x => x.AttributeType.Name == nameof(AssemblyMetadataAttribute)
	&& x.ConstructorArguments[0].Value?.ToString() == "OrderAfter").Select(x => x.ConstructorArguments[1].Value?.ToString()).ToArray();

if (!Directory.Exists(outputPath))
	Directory.CreateDirectory(outputPath);
using var writer = new StreamWriter(Path.Combine(outputPath, "About.xml"), new FileStreamOptions {
	Mode = FileMode.Create,
	Access = FileAccess.ReadWrite,
});
writer.Write(@$"<?xml version=""1.0"" encoding=""utf-8""?>
<!-- This file is auto-generated by AboutGenerator tool. Do not edit manually - it will be overwritten on next build. -->
<!-- Edit the assembly attributes in AssemblyInfo.cs file of the mod instead. -->
<ModMetadata xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
	<ModID>{id}</ModID>
	<Name>{title}</Name>
	<Author>{author}</Author>
	<Version>{version}</Version>
	<Description>{description}</Description>
	<InGameDescription>{inGameDescription}</InGameDescription>
	{(changelog != null ? $"<ChangeLog>\r\n{changelog}\r\n\t</ChangeLog>" : "")}
	{(workshopHandle != null ? $"<WorkshopHandle>{workshopHandle}</WorkshopHandle>" : "")}
	{(tags.Any() ? $"<Tags>{string.Concat(tags.Select(tag => $"\r\n\t\t<Tag>{tag}</Tag>"))}\r\n\t</Tags>" : "<Tags />")}
{string.Concat(orderBefore.Select(x => $"\r\n\t<OrderBefore {x} />"))}
{string.Concat(orderAfter.Select(x => $"\r\n\t<OrderAfter {x} />"))}
{string.Concat(dependencies.Select(x => $"\r\n\t<DependsOn {x} />"))}
</ModMetadata>");
writer.Flush();

return 0;
