//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:/Repo/Mods/Stationeers/Entropy/Assets/Scripts/MIPSParser/MIPS.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMIPSListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
public partial class MIPSBaseListener : IMIPSListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] MIPSParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] MIPSParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] MIPSParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] MIPSParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] MIPSParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] MIPSParser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefine([NotNull] MIPSParser.DefineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefine([NotNull] MIPSParser.DefineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlias([NotNull] MIPSParser.AliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlias([NotNull] MIPSParser.AliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] MIPSParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] MIPSParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.define_target"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefine_target([NotNull] MIPSParser.Define_targetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.define_target"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefine_target([NotNull] MIPSParser.Define_targetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.alias_target"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlias_target([NotNull] MIPSParser.Alias_targetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.alias_target"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlias_target([NotNull] MIPSParser.Alias_targetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] MIPSParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] MIPSParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperation([NotNull] MIPSParser.OperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperation([NotNull] MIPSParser.OperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperand([NotNull] MIPSParser.OperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperand([NotNull] MIPSParser.OperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] MIPSParser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] MIPSParser.CommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.register"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegister([NotNull] MIPSParser.RegisterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.register"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegister([NotNull] MIPSParser.RegisterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.device"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDevice([NotNull] MIPSParser.DeviceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.device"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDevice([NotNull] MIPSParser.DeviceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIPSParser.hash"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHash([NotNull] MIPSParser.HashContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIPSParser.hash"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHash([NotNull] MIPSParser.HashContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
